#!/usr/bin/env bash
set -euo pipefail

ncu_command="${NCU:-ncu}"
executable="examples/gemm/cublaslt_profiler"
manifest=""
output_dir=""
iterations=1

usage() {
  cat <<'EOF'
Capture the actual cuBLASLt kernel for every shape in a Qwen manifest.

Usage:
  bash tools/qwen_gemm/capture_ncu_candidates.sh [options]

Options:
  --manifest FILE      Shape manifest generated by generate_qwen_shapes.py
  --output-dir DIR     Directory for .ncu-rep, raw CSV, and capture_index.csv
  --executable FILE    Profiled cuBLASLt executable
  --iterations N       Profiler iterations per shape (default: 1)
  --ncu PATH           NCU executable (default: $NCU or ncu)
EOF
}

while (($#)); do
  case "$1" in
    --manifest) manifest="$2"; shift 2 ;;
    --output-dir) output_dir="$2"; shift 2 ;;
    --executable) executable="$2"; shift 2 ;;
    --iterations) iterations="$2"; shift 2 ;;
    --ncu) ncu_command="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ -n "$manifest" && -f "$manifest" ]] ||
  { echo "A valid --manifest is required." >&2; exit 2; }
[[ -n "$output_dir" ]] ||
  { echo "--output-dir is required." >&2; exit 2; }
[[ -x "$executable" ]] ||
  { echo "Profiler executable is not executable: $executable" >&2; exit 2; }
[[ "$iterations" =~ ^[1-9][0-9]*$ ]] ||
  { echo "--iterations must be positive." >&2; exit 2; }
command -v "$ncu_command" >/dev/null 2>&1 ||
  { echo "NCU not found: $ncu_command" >&2; exit 2; }

mkdir -p "$output_dir/reports" "$output_dir/csv"
index_file="$output_dir/capture_index.csv"
printf '%s\n' \
  'case_id,m,n,k,trans,batch_count,operand_a,operand_b,models,stages,operations,lengths,kernel_report,raw_csv' \
  > "$index_file"

case_id=0
while IFS=',' read -r m n k trans batch_count operand_a operand_b models stages operations lengths; do
  [[ "$m" == "m" ]] && continue
  case_id=$((case_id + 1))
  tag=$(printf '%05d_m%s_n%s_k%s_%s_b%s' \
    "$case_id" "$m" "$n" "$k" "$trans" "$batch_count")
  report_prefix="$output_dir/reports/$tag"
  report_file="$report_prefix.ncu-rep"
  raw_csv="$output_dir/csv/$tag.csv"

  echo "[NCU $case_id] MxNxK=${m}x${n}x${k} trans=$trans batch=$batch_count"
  "$ncu_command" --target-processes all --set basic --force-overwrite \
    --kernel-name-base demangled -o "$report_prefix" \
    "$executable" "--m=$m" "--n=$n" "--k=$k" "--trans=$trans" \
    "--batch-count=$batch_count" "--iterations=$iterations"
  "$ncu_command" --import "$report_file" --csv --page raw > "$raw_csv"

  # Manifest fields do not contain commas; preserve the exact strings for
  # traceability while keeping the index consumable by csv.DictReader.
  printf '%s,%s,%s,%s,%s,%s,%s,%s,"%s","%s","%s","%s",%s,%s\n' \
    "$case_id" "$m" "$n" "$k" "$trans" "$batch_count" \
    "$operand_a" "$operand_b" "$models" "$stages" "$operations" "$lengths" \
    "$report_file" "$raw_csv" >> "$index_file"
done < "$manifest"

echo "NCU capture complete: $index_file"
