#!/usr/bin/env python3
"""Generate strict CUTLASS dispatch entries from NCU-exact CTA data."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


REQUIRED = (
    "accumulator", "m", "n", "k", "trans", "batch_count",
    "layout_a", "layout_b", "layout_c",
    "align_a", "align_b", "align_c",
    "ncu_tb_m", "ncu_tb_n", "ncu_tb_k",
    "warp_m", "warp_n", "warp_k",
    "swizzle", "ncu_stages", "split_k",
)

ACCUMULATORS = {
    "fp16": "cutlass::half_t",
    "half": "cutlass::half_t",
    "fp32": "float",
    "float": "float",
}

SWIZZLES = {
    "Identity": "cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>",
    "Stream-K": "cutlass::gemm::threadblock::ThreadblockSwizzleStreamK",
}


def positive(row: dict[str, str], name: str) -> int:
    value = int(row[name])
    if value <= 0:
        raise ValueError(f"{name} must be positive, got {value}")
    return value


def validate(row: dict[str, str], line: int) -> None:
    missing = [name for name in REQUIRED if not row.get(name, "").strip()]
    if missing:
        raise ValueError(f"line {line}: missing {', '.join(missing)}")
    if row["accumulator"] not in ACCUMULATORS:
        raise ValueError(f"line {line}: unsupported accumulator {row['accumulator']}")
    if row["swizzle"] not in SWIZZLES:
        raise ValueError(f"line {line}: unsupported swizzle {row['swizzle']}")
    if row["trans"] not in ("NN", "NT", "TN", "TT"):
        raise ValueError(f"line {line}: unsupported trans {row['trans']}")

    tb = [positive(row, name) for name in ("ncu_tb_m", "ncu_tb_n", "ncu_tb_k")]
    warp = [positive(row, name) for name in ("warp_m", "warp_n", "warp_k")]
    positive(row, "ncu_stages")
    positive(row, "batch_count")
    for name in ("m", "n", "k"):
        positive(row, name)
    for name in ("align_a", "align_b", "align_c"):
        if positive(row, name) not in (1, 2, 4, 8):
            raise ValueError(f"line {line}: {name} must be 1, 2, 4, or 8")
    if any(tile % part for tile, part in zip(tb, warp)):
        raise ValueError(
            f"line {line}: NCU CTA {tb} must be divisible by CUTLASS warp {warp}"
        )
    if int(row["split_k"]) < 1:
        raise ValueError(f"line {line}: split_k must be at least 1")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Preserve NCU CTA M/N/K and stages in CUTLASS exact entries.")
    parser.add_argument("--input", type=Path, required=True,
                        help="CSV containing NCU-exact and CUTLASS completion fields")
    parser.add_argument(
        "--output", type=Path,
        default=Path("examples/gemm/ncu_exact_configurations.inc"))
    args = parser.parse_args()

    with args.input.open(encoding="utf-8", newline="") as stream:
        rows = list(csv.DictReader(stream))
    if not rows:
        raise ValueError("input contains no configurations")

    configurations: set[tuple[str, ...]] = set()
    lines = [
        "// Generated by generate_ncu_exact_configurations.py; do not edit.",
        "// ncu_tb_m/n/k and ncu_stages are copied verbatim from the input.",
        "// Warp/layout/alignment/swizzle/split-K are explicit CUTLASS completion fields.",
        "",
    ]
    for line_number, row in enumerate(rows, start=2):
        row = {key: (value or "").strip() for key, value in row.items()}
        validate(row, line_number)
        configuration = tuple(row[name] for name in REQUIRED)
        if configuration in configurations:
            raise ValueError(
                f"line {line_number}: duplicate exact configuration")
        configurations.add(configuration)
        lines.extend([
            f"// source=parsed:verified-ncu-kernel-name-schema CTA={row['ncu_tb_m']}x"
            f"{row['ncu_tb_n']}x{row['ncu_tb_k']} stages={row['ncu_stages']}; "
            "warp/layout/alignment/swizzle/split-K=provided:cutlass-completion",
            f"GEMM_NCU_EXACT_ENTRY({ACCUMULATORS[row['accumulator']]}, "
            f"{row['m']}, {row['n']}, {row['k']}, \"{row['trans']}\", "
            f"{row['batch_count']},",
            f"    {row['layout_a']}, {row['layout_b']}, {row['layout_c']}, "
            f"{row['align_a']}, {row['align_b']}, {row['align_c']},",
            f"    {row['ncu_tb_m']}, {row['ncu_tb_n']}, {row['ncu_tb_k']}, "
            f"{row['warp_m']}, {row['warp_n']}, {row['warp_k']},",
            f"    {SWIZZLES[row['swizzle']]}, {row['ncu_stages']}, "
            f"{row['split_k']})",
            "",
        ])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Generated {len(rows)} NCU-exact mappings in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
